.PHONY: clean All

All:
	@echo "----------Building project:[ pointerMath1 - Debug ]----------"
	@cd "pointerMath1" && "$(MAKE)" -f  "pointerMath1.mk"
clean:
	@echo "----------Cleaning project:[ pointerMath1 - Debug ]----------"
	@cd "pointerMath1" && "$(MAKE)" -f  "pointerMath1.mk" clean
